
// Helper to get day index
const getDailyIndex = (arrayLength) => {
  const today = new Date();
  const daysSinceEpoch = Math.floor(today.getTime() / (1000 * 60 * 60 * 24));
  return daysSinceEpoch % arrayLength;
};

export const drawingTips = [
  { title: "Draw a Happy Cat", emoji: "🐱", description: "Let's draw a purr-fectly happy kitty!", steps: [{ text: "Draw a big round circle for the head", emoji: "⚪" }, { text: "Add two pointy triangles for ears on top", emoji: "🔺" }, { text: "Draw two dots for eyes and a tiny 'w' for the mouth", emoji: "😺" }] },
  { title: "Silly Robot", emoji: "🤖", description: "Beep boop! Build a friendly drawing of a robot.", steps: [{ text: "Draw a square for the robot's head", emoji: "⬜" }, { text: "Add a rectangle below it for the body", emoji: "🔲" }, { text: "Draw zig-zag lines for the arms and legs", emoji: "⚡" }] },
  { title: "Cute Little Bird", emoji: "🐦", description: "Tweet tweet! Let's make a feathered friend.", steps: [{ text: "Draw a shape like an egg for the body", emoji: "🥚" }, { text: "Add a tiny triangle on the side for the beak", emoji: "🔽" }, { text: "Draw two little lines at the bottom for legs", emoji: "📏" }] },
  { title: "Friendly Monster", emoji: "👾", description: "Create a monster that loves to give hugs!", steps: [{ text: "Draw a big jellybean shape", emoji: "🥔" }, { text: "Add three big circles for eyes", emoji: "👀" }, { text: "Draw a wide, toothy smile!", emoji: "😁" }] },
  { title: "Speedy Rocket", emoji: "🚀", description: "Blast off into space with this rocket drawing.", steps: [{ text: "Draw a tall oval that points up", emoji: "🪺" }, { text: "Add two triangles on the bottom sides for fins", emoji: "📐" }, { text: "Draw squiggly fire coming out the bottom", emoji: "🔥" }] },
  { title: "Bouncing Frog", emoji: "🐸", description: "Ribbit! Draw a frog ready to jump.", steps: [{ text: "Draw a wide oval for the frog's body", emoji: "🟢" }, { text: "Add two bumps on top for the eyes", emoji: "👀" }, { text: "Draw a huge smile from cheek to cheek", emoji: "〰️" }] },
  { title: "Yummy Ice Cream", emoji: "🍦", description: "The sweetest drawing you'll make today!", steps: [{ text: "Draw a V-shape for the cone", emoji: "🔽" }, { text: "Draw fluffy cloud shapes on top for the ice cream", emoji: "☁️" }, { text: "Add a little circle on the very top for a cherry", emoji: "🍒" }] },
  { title: "Happy Star", emoji: "⭐", description: "Shine bright with this easy star drawing.", steps: [{ text: "Draw an upside-down V", emoji: "/\ " }, { text: "Cross it with a horizontal line", emoji: "➖" }, { text: "Connect the bottom points to the opposite ends", emoji: "✨" }] },
  { title: "Sleepy Bear", emoji: "🐻", description: "Draw a bear getting ready for a nap.", steps: [{ text: "Draw a large circle for the head", emoji: "⭕" }, { text: "Add two small half-circles for the ears", emoji: "👂" }, { text: "Draw two curved lines for closed, sleepy eyes", emoji: "😌" }] },
  { title: "Racing Car", emoji: "🚗", description: "Vroom vroom! Draw a super fast car.", steps: [{ text: "Draw a long rectangle for the car body", emoji: "▭" }, { text: "Add a smaller rectangle on top for the windows", emoji: "🪟" }, { text: "Draw two circles at the bottom for wheels", emoji: "🍩" }] },
  { title: "Magical Unicorn", emoji: "🦄", description: "Create a beautiful mythical creature.", steps: [{ text: "Draw a horse head shape", emoji: "🐴" }, { text: "Add a spiral cone on the forehead", emoji: "🍦" }, { text: "Draw a wavy, flowing mane", emoji: "🌊" }] },
  { title: "Friendly Sun", emoji: "☀️", description: "Warm up your paper with a smiling sun.", steps: [{ text: "Draw a perfect circle in the middle", emoji: "🟡" }, { text: "Draw short and long lines all around it", emoji: "🔆" }, { text: "Give it cool sunglasses and a smile", emoji: "😎" }] },
  { title: "Busy Bee", emoji: "🐝", description: "Buzz buzz! Draw a cute bumblebee.", steps: [{ text: "Draw a fat oval shape", emoji: "🥔" }, { text: "Draw three stripes across its body", emoji: "🦓" }, { text: "Add two little loops on top for wings", emoji: "🦋" }] },
  { title: "Jumping Dolphin", emoji: "🐬", description: "Draw a dolphin playing in the waves.", steps: [{ text: "Draw a curved banana shape", emoji: "🍌" }, { text: "Add a pointy fin on its back", emoji: "🦈" }, { text: "Draw a wide tail at the back", emoji: "🧜‍♀️" }] },
  { title: "Giant Dinosaur", emoji: "🦖", description: "Roar! Draw a mighty T-Rex.", steps: [{ text: "Draw a big rounded block for the head and body", emoji: "🟩" }, { text: "Add tiny arms and big strong legs", emoji: "💪" }, { text: "Draw zig-zag spikes all down its back", emoji: "⛰️" }] },
  { title: "Fluffy Sheep", emoji: "🐑", description: "Baa! Draw a wooly little friend.", steps: [{ text: "Draw a big puffy cloud shape", emoji: "☁️" }, { text: "Draw a small oval for the face", emoji: "🥔" }, { text: "Add four little stick legs below", emoji: "🥢" }] },
  { title: "Colorful Butterfly", emoji: "🦋", description: "Draw a butterfly with huge wings.", steps: [{ text: "Draw a thin hotdog shape for the body", emoji: "🌭" }, { text: "Draw a big number '3' on the right for wings", emoji: "3️⃣" }, { text: "Draw a backwards '3' on the left side", emoji: "🪞" }] },
  { title: "Sneaky Snake", emoji: "🐍", description: "Sssss! Draw a slithering snake.", steps: [{ text: "Draw a long, squiggly 'S' line", emoji: "〰️" }, { text: "Draw another line right next to it", emoji: "🛤️" }, { text: "Add a diamond-shaped head and a split tongue", emoji: "👅" }] },
  { title: "Wise Owl", emoji: "🦉", description: "Hoot hoot! Draw a smart night bird.", steps: [{ text: "Draw an oval with two tufts on top", emoji: "🥚" }, { text: "Draw two giant circles for eyes", emoji: "🥽" }, { text: "Add a tiny triangle beak between the eyes", emoji: "🔽" }] },
  { title: "Cheeky Monkey", emoji: "🐒", description: "Ooh ooh ah ah! Let's draw a monkey.", steps: [{ text: "Draw a circle for the head and an oval below it", emoji: "⛄" }, { text: "Add two big C-shapes for ears on the sides", emoji: "👂" }, { text: "Draw a long, curly tail", emoji: "➰" }] },
  { title: "Spiky Hedgehog", emoji: "🦔", description: "Draw a cute, prickly buddy.", steps: [{ text: "Draw a half-circle resting on a flat line", emoji: "🧲" }, { text: "Add a little pointy nose on one side", emoji: "📍" }, { text: "Draw lots of short, spiky lines on its back", emoji: "🌵" }] },
  { title: "Happy Turtle", emoji: "🐢", description: "Slow and steady! Draw a friendly turtle.", steps: [{ text: "Draw a large dome shape for the shell", emoji: "🪖" }, { text: "Add hexagon patterns on the shell", emoji: "🛑" }, { text: "Draw a head, four legs, and a tiny tail popping out", emoji: "🐾" }] },
  { title: "Dancing Penguin", emoji: "🐧", description: "Waddle waddle! Draw a penguin.", steps: [{ text: "Draw a shape like a bowling pin", emoji: "🎳" }, { text: "Draw a smaller oval inside for the white belly", emoji: "⚪" }, { text: "Add flippers and little orange feet", emoji: "🦶" }] },
  { title: "Brave Lion", emoji: "🦁", description: "Roar! Draw the king of the jungle.", steps: [{ text: "Draw a circle for the face", emoji: "🟡" }, { text: "Draw a huge, fluffy zig-zag mane around it", emoji: "💥" }, { text: "Add a triangle nose and a confident smile", emoji: "😺" }] },
  { title: "Clever Fox", emoji: "🦊", description: "Draw a sly little fox.", steps: [{ text: "Draw a triangle pointing down for the face", emoji: "🔻" }, { text: "Add two big triangle ears on top", emoji: "🔺" }, { text: "Draw a big, bushy tail with a white tip", emoji: "🖌️" }] },
  { title: "Playful Puppy", emoji: "🐶", description: "Woof! Draw a dog waiting for a bone.", steps: [{ text: "Draw a rounded square for the head", emoji: "🔲" }, { text: "Add floppy ears dropping down the sides", emoji: "💧" }, { text: "Draw a wagging tail making motion lines", emoji: "💓" }] },
  { title: "Slow Snail", emoji: "🐌", description: "Draw a snail carrying its house.", steps: [{ text: "Draw a big spiral for the shell", emoji: "🌀" }, { text: "Draw a long, soft body underneath", emoji: "🐛" }, { text: "Add two tall antennas with eyes on top", emoji: "📡" }] },
  { title: "Hungry Mouse", emoji: "🐭", description: "Squeak! Draw a tiny mouse.", steps: [{ text: "Draw a small teardrop shape", emoji: "💧" }, { text: "Add two giant round ears", emoji: "👂" }, { text: "Draw a long, thin, curly tail", emoji: "〰️" }] },
  { title: "Leaping Kangaroo", emoji: "🦘", description: "Boing! Draw a bouncing kangaroo.", steps: [{ text: "Draw a pear shape for the body", emoji: "🍐" }, { text: "Add two huge feet at the bottom", emoji: "🦶" }, { text: "Draw a little pocket pouch on its tummy", emoji: "🎒" }] },
  { title: "Quiet Sloth", emoji: "🦥", description: "Draw a relaxed, hanging sloth.", steps: [{ text: "Draw a tree branch straight across", emoji: "🪵" }, { text: "Draw a hairy body hanging upside down", emoji: "🧶" }, { text: "Add a sweet, sleepy face with a dark mask", emoji: "🦹" }] }
];

export const storyStarters = [
  { title: "The Magic Backpack", emoji: "🎒", encouragement: "What amazing things will you find?", steps: [{ text: "Introduce a kid who finds a glowing backpack", emoji: "✨" }, { text: "Describe the first magical item they pull out", emoji: "🪄" }, { text: "Tell how they use it to help a friend", emoji: "🤝" }] },
  { title: "The Talking Dog", emoji: "🐕", encouragement: "Dogs have a lot to say!", steps: [{ text: "Your pet dog suddenly starts speaking English", emoji: "🗣️" }, { text: "The dog tells you a big secret about the neighborhood", emoji: "🤫" }, { text: "You both go on a mission to solve the mystery", emoji: "🕵️" }] },
  { title: "Planet Candy", emoji: "🍬", encouragement: "A sweet adventure awaits!", steps: [{ text: "You discover a rocket ship in your backyard", emoji: "🚀" }, { text: "You fly to a planet made entirely of candy", emoji: "🍭" }, { text: "You meet the gummy bear king who needs your help", emoji: "👑" }] },
  { title: "The Tiny Door", emoji: "🚪", encouragement: "Where does it lead?", steps: [{ text: "You find a door the size of your hand in your room", emoji: "✋" }, { text: "You shrink down to fit through it", emoji: "🤏" }, { text: "Describe the miniature world you discover inside", emoji: "🍄" }] },
  { title: "The Flying Bicycle", emoji: "🚲", encouragement: "Pedal up to the clouds!", steps: [{ text: "Your bicycle starts floating when you pedal fast", emoji: "☁️" }, { text: "You fly over your town and see something strange", emoji: "🦅" }, { text: "You rescue a stuck kite from a giant tree", emoji: "🪁" }] },
  { title: "The Dinosaur Egg", emoji: "🥚", encouragement: "A prehistoric surprise!", steps: [{ text: "You find a giant spotted egg in the park", emoji: "🌳" }, { text: "It hatches into a friendly baby dinosaur", emoji: "🦕" }, { text: "You have to hide it from your parents", emoji: "🙈" }] },
  { title: "The Invisible Paint", emoji: "🎨", encouragement: "Now you see it, now you don't!", steps: [{ text: "You mix some paints and it turns things invisible", emoji: "🫥" }, { text: "You paint your treehouse to hide it", emoji: "🏡" }, { text: "You play the best game of hide and seek ever", emoji: "🫣" }] },
  { title: "The Weather Machine", emoji: "🌤️", encouragement: "You control the skies!", steps: [{ text: "You find a remote control that changes the weather", emoji: "📺" }, { text: "You accidentally make it snow in summer", emoji: "❄️" }, { text: "You have to figure out how to fix it before school", emoji: "🏫" }] },
  { title: "The Library Ghost", emoji: "👻", encouragement: "A friendly spirit needs you.", steps: [{ text: "A ghost in the library keeps dropping books", emoji: "📚" }, { text: "You find out the ghost just wants someone to read to them", emoji: "📖" }, { text: "You read them the best story ever", emoji: "🌟" }] },
  { title: "The Super Shoes", emoji: "👟", encouragement: "Lace up for super speed!", steps: [{ text: "You put on new shoes that make you super fast", emoji: "⚡" }, { text: "You enter a race against a cheetah", emoji: "🐆" }, { text: "You learn that going fast isn't always the best way", emoji: "🐢" }] },
  { title: "The Ocean Kingdom", emoji: "🧜‍♀️", encouragement: "Dive into a deep sea story!", steps: [{ text: "You find a seashell that lets you breathe underwater", emoji: "🐚" }, { text: "You swim down and meet a mermaid princess", emoji: "👑" }, { text: "You help her find her lost pearl necklace", emoji: "🦪" }] },
  { title: "The Robot Teacher", emoji: "🤖", encouragement: "School just got much cooler!", steps: [{ text: "Your new substitute teacher is a robot", emoji: "👨‍🏫" }, { text: "The robot goes crazy when someone drops a magnet", emoji: "🧲" }, { text: "You use your science skills to reboot the teacher", emoji: "💻" }] },
  { title: "The Time Watch", emoji: "⌚", encouragement: "Travel through time!", steps: [{ text: "Your grandfather gives you a watch that stops time", emoji: "⏳" }, { text: "You pause time to catch a falling vase", emoji: "🏺" }, { text: "You get stuck and have to find the magic key to restart it", emoji: "🗝️" }] },
  { title: "The Cloud Castle", emoji: "🏰", encouragement: "A castle in the sky!", steps: [{ text: "You climb a giant beanstalk into the clouds", emoji: "🌱" }, { text: "You find a castle made of fluffy white clouds", emoji: "☁️" }, { text: "You have a bouncing contest with the cloud guards", emoji: "🤸" }] },
  { title: "The Animal Translator", emoji: "🎧", encouragement: "What are they saying?", steps: [{ text: "You invent headphones that let you understand animals", emoji: "🐿️" }, { text: "The squirrels tell you about a hidden treasure", emoji: "💎" }, { text: "You follow their map to find a chest of golden acorns", emoji: "🌰" }] },
  { title: "The Magic Crayon", emoji: "🖍️", encouragement: "Draw your dreams to life!", steps: [{ text: "Everything you draw with a red crayon becomes real", emoji: "🎈" }, { text: "You draw a giant slide out your bedroom window", emoji: "🛝" }, { text: "You invite the whole town to play on it", emoji: "🏘️" }] },
  { title: "The Shrinking Potion", emoji: "🧪", encouragement: "A tiny adventure!", steps: [{ text: "You drink a potion and shrink to the size of a bug", emoji: "🐜" }, { text: "You have to cross the backyard jungle", emoji: "🌿" }, { text: "You make friends with a helpful ladybug", emoji: "🐞" }] },
  { title: "The Moon Landing", emoji: "🌕", encouragement: "One giant leap for kids!", steps: [{ text: "You build a cardboard rocket that actually works", emoji: "📦" }, { text: "You land on the moon and find moon aliens", emoji: "👽" }, { text: "You teach them how to play tag in low gravity", emoji: "🏃" }] },
  { title: "The Talking Tree", emoji: "🌲", encouragement: "Nature has a voice!", steps: [{ text: "The old oak tree in the park says hello to you", emoji: "👋" }, { text: "It tells you a story from 100 years ago", emoji: "🕰️" }, { text: "You help the tree protect a bird's nest from the wind", emoji: "🌬️" }] },
  { title: "The Secret Map", emoji: "🗺️", encouragement: "X marks the spot!", steps: [{ text: "You find an old map hidden inside a library book", emoji: "📜" }, { text: "The clues lead you through your own house", emoji: "🏠" }, { text: "The treasure turns out to be a box of ancient cookies", emoji: "🍪" }] },
  { title: "The Music Maker", emoji: "🎸", encouragement: "Play a magical tune!", steps: [{ text: "You find a guitar that makes everyone dance", emoji: "💃" }, { text: "You play it at a grumpy giant's cave", emoji: "🧌" }, { text: "The giant laughs, dances, and becomes your friend", emoji: "😂" }] },
  { title: "The Bubble Boy", emoji: "🫧", encouragement: "Float away!", steps: [{ text: "You blow a giant bubble and get trapped inside it", emoji: "🎈" }, { text: "You float all the way to the top of the mountains", emoji: "🏔️" }, { text: "An eagle gently pops it to save you", emoji: "🦅" }] },
  { title: "The Night Sun", emoji: "🌞", encouragement: "A bright mystery!", steps: [{ text: "You wake up at midnight, but the sun is shining brightly", emoji: "😎" }, { text: "You realize the sun couldn't sleep and wanted to play", emoji: "🥱" }, { text: "You sing the sun a lullaby to put it back to bed", emoji: "🎶" }] },
  { title: "The Ice Skater", emoji: "⛸️", encouragement: "Glide on ice!", steps: [{ text: "You find ice skates that make you a professional skater", emoji: "🥇" }, { text: "You enter the town's winter festival competition", emoji: "❄️" }, { text: "You do a spin so fast you create a mini snow tornado", emoji: "🌪️" }] },
  { title: "The Mirror World", emoji: "🪞", encouragement: "Everything is backwards!", steps: [{ text: "You step through the mirror in the hallway", emoji: "🚶" }, { text: "In this world, cats bark and dogs meow", emoji: "🐈" }, { text: "You have to walk backwards to get back home", emoji: "🔙" }] },
  { title: "The Friendly Dragon", emoji: "🐉", encouragement: "A fiery friend!", steps: [{ text: "A dragon lands on your school roof", emoji: "🏫" }, { text: "It turns out he just wants to learn math", emoji: "➕" }, { text: "You become his tutor and he gives you a ride home", emoji: "🎒" }] },
  { title: "The Lost Shadow", emoji: "👤", encouragement: "Where did it go?", steps: [{ text: "You wake up and your shadow has run away", emoji: "🏃" }, { text: "You follow its footprints to the park", emoji: "👣" }, { text: "You find it playing on the swings and join in", emoji: "🛝" }] },
  { title: "The Space Pirate", emoji: "🏴‍☠️", encouragement: "Ahoy, aliens!", steps: [{ text: "A pirate ship sails down from the stars", emoji: "🌠" }, { text: "The captain asks you to help find the Milky Way Treasure", emoji: "🌌" }, { text: "You defeat a space octopus with a laser sword", emoji: "🐙" }] },
  { title: "The Giant Pumpkin", emoji: "🎃", encouragement: "A massive squash!", steps: [{ text: "You plant a magic seed and a pumpkin grows as big as a house", emoji: "🏠" }, { text: "You carve a door in it and make it your secret base", emoji: "🚪" }, { text: "You invite your friends over for a pumpkin party", emoji: "🎉" }] },
  { title: "The Whispering Wind", emoji: "🌬️", encouragement: "Listen closely!", steps: [{ text: "The wind whispers a riddle in your ear", emoji: "🧩" }, { text: "You solve the riddle and a secret path opens up", emoji: "🛣️" }, { text: "The path leads to a garden where flowers sing", emoji: "🌷" }] }
];

export const craftIdeas = [
  { title: "Toilet Paper Roll Binoculars", emoji: "🔭", materials: ["2 toilet paper rolls", "String", "Tape or glue", "Crayons or markers"], difficulty: "Easy", steps: [{ text: "Tape the two rolls together side by side", emoji: "🧻" }, { text: "Decorate them with your favorite colors and shapes", emoji: "🖍️" }, { text: "Tape the string to the sides so you can wear them", emoji: "🧵" }] },
  { title: "Paper Plate Monster", emoji: "👾", materials: ["1 paper plate", "Paint or markers", "Googly eyes", "Construction paper"], difficulty: "Easy", steps: [{ text: "Paint the whole paper plate a silly color", emoji: "🎨" }, { text: "Glue as many googly eyes as you want in the middle", emoji: "👀" }, { text: "Cut out zig-zag teeth from paper and glue them on", emoji: "✂️" }] },
  { title: "Sock Puppet Buddy", emoji: "🧦", materials: ["An old clean sock", "Buttons or markers", "Yarn", "Glue"], difficulty: "Medium", steps: [{ text: "Put the sock on your hand to find where the mouth goes", emoji: "✋" }, { text: "Glue two buttons on top for eyes", emoji: "🔘" }, { text: "Glue pieces of yarn on the top for crazy hair", emoji: "🧶" }] },
  { title: "Popsicle Stick Plane", emoji: "🛩️", materials: ["3 Popsicle sticks", "1 Clothespin", "Glue", "Paint"], difficulty: "Medium", steps: [{ text: "Paint the clothespin and sticks in cool racing colors", emoji: "🖌️" }, { text: "Glue two sticks across the front of the clothespin for main wings", emoji: "➕" }, { text: "Glue the last stick on the back for the tail wing", emoji: "🛫" }] },
  { title: "Nature Collage", emoji: "🍃", materials: ["Fallen leaves", "Small twigs", "Glue", "A piece of thick paper"], difficulty: "Easy", steps: [{ text: "Go on a nature walk and collect pretty leaves and twigs", emoji: "🚶" }, { text: "Arrange them on your paper to look like an animal or house", emoji: "🦁" }, { text: "Carefully glue everything down and let it dry", emoji: "🧴" }] },
  { title: "Cardboard Tube Rocket", emoji: "🚀", materials: ["Paper towel roll", "Cardboard scraps", "Foil", "Tape"], difficulty: "Medium", steps: [{ text: "Wrap the paper towel roll in shiny aluminum foil", emoji: "✨" }, { text: "Cut three triangles from cardboard and tape them to the bottom", emoji: "📐" }, { text: "Make a cardboard cone and tape it to the top", emoji: "🔺" }] },
  { title: "Coffee Filter Sun", emoji: "☀️", materials: ["1 Coffee filter", "Yellow/Orange markers", "Water spray bottle"], difficulty: "Easy", steps: [{ text: "Color the coffee filter with yellow and orange markers", emoji: "🖍️" }, { text: "Lightly spray it with water and watch the colors mix", emoji: "💦" }, { text: "Let it dry, then hang it in your window to catch the light", emoji: "🪟" }] },
  { title: "Pasta Necklace", emoji: "📿", materials: ["Uncooked tube pasta", "Yarn", "Paint or food coloring"], difficulty: "Medium", steps: [{ text: "Paint the dry pasta tubes in different bright colors", emoji: "🌈" }, { text: "Wait for them to dry completely", emoji: "⏳" }, { text: "String them onto the yarn and tie it around your neck", emoji: "🎀" }] },
  { title: "Egg Carton Train", emoji: "🚂", materials: ["Half an egg carton", "Paint", "Cardboard circles (for wheels)", "Glue"], difficulty: "Easy", steps: [{ text: "Paint the egg carton to look like train cars", emoji: "🚆" }, { text: "Glue cardboard circles on the sides for wheels", emoji: "🍩" }, { text: "Put small toys inside to take them on a ride", emoji: "🧸" }] },
  { title: "Paper Bag Mask", emoji: "🎭", materials: ["Brown paper grocery bag", "Scissors", "Markers", "Yarn"], difficulty: "Hard", steps: [{ text: "Have an adult help you cut eye holes in the bag", emoji: "✂️" }, { text: "Draw an animal face on the front with big markers", emoji: "🦁" }, { text: "Glue yarn on the sides for whiskers or a mane", emoji: "🧶" }] },
  { title: "Magic Wand", emoji: "🪄", materials: ["A straight stick", "Ribbons", "Foil", "Tape"], difficulty: "Easy", steps: [{ text: "Cut a star shape out of thick paper and wrap it in foil", emoji: "⭐" }, { text: "Tape the star firmly to the top of your stick", emoji: "📏" }, { text: "Tie colorful ribbons right under the star so they flow", emoji: "🎀" }] },
  { title: "Pet Rock", emoji: "🪨", materials: ["A smooth rock", "Paint", "Googly eyes", "Glue"], difficulty: "Easy", steps: [{ text: "Wash your rock and dry it off", emoji: "🧼" }, { text: "Paint it your favorite color and let it dry", emoji: "🎨" }, { text: "Glue on googly eyes and paint a happy smile", emoji: "😁" }] },
  { title: "Sponge Butterflies", emoji: "🧽", materials: ["Kitchen sponges", "String", "Paint", "Paper"], difficulty: "Medium", steps: [{ text: "Tie a string tightly around the middle of a sponge to make wings", emoji: "🎀" }, { text: "Dip the sponge wings into different paint colors", emoji: "🎨" }, { text: "Press it onto paper like a stamp to make butterfly art", emoji: "🦋" }] },
  { title: "Cardboard Guitar", emoji: "🎸", materials: ["Empty tissue box", "Rubber bands", "Paper towel roll", "Tape"], difficulty: "Hard", steps: [{ text: "Tape the paper towel roll to the top of the box for the neck", emoji: "📏" }, { text: "Have an adult cut a hole in the front of the tissue box", emoji: "✂️" }, { text: "Stretch rubber bands around the box over the hole to strum", emoji: "🎶" }] },
  { title: "Tin Can Frog", emoji: "🐸", materials: ["Clean empty tin can", "Green paint", "Paper", "Glue"], difficulty: "Medium", steps: [{ text: "Paint the outside of the tin can green", emoji: "🟢" }, { text: "Cut out four frog legs from green paper", emoji: "🦵" }, { text: "Glue the legs to the bottom and draw a face on the front", emoji: "🐸" }] },
  { title: "Cotton Ball Cloud", emoji: "☁️", materials: ["Cotton balls", "Blue paper", "Glue", "White crayon"], difficulty: "Easy", steps: [{ text: "Draw a big cloud outline on the blue paper", emoji: "🖍️" }, { text: "Put glue all inside the lines", emoji: "🧴" }, { text: "Stick fluffy cotton balls all over to make a 3D cloud", emoji: "☁️" }] },
  { title: "Button Tree Art", emoji: "🌳", materials: ["Lots of colorful buttons", "Brown marker", "Glue", "Paper"], difficulty: "Medium", steps: [{ text: "Draw a tree trunk and branches with the brown marker", emoji: "🪵" }, { text: "Put drops of glue all along the branches", emoji: "💧" }, { text: "Stick colorful buttons on the glue to look like magical leaves", emoji: "🔘" }] },
  { title: "Tissue Paper Flower", emoji: "🌺", materials: ["Colorful tissue paper", "Pipe cleaners", "Scissors"], difficulty: "Medium", steps: [{ text: "Stack 4 sheets of tissue paper and fold them like an accordion", emoji: "🪗" }, { text: "Wrap a pipe cleaner tightly around the middle", emoji: "🧵" }, { text: "Carefully pull each layer of paper up to make petals bloom", emoji: "🌸" }] },
  { title: "Paper Crown", emoji: "👑", materials: ["Yellow construction paper", "Stickers or jewels", "Stapler or tape"], difficulty: "Easy", steps: [{ text: "Cut zig-zags along the top of a long strip of yellow paper", emoji: "✂️" }, { text: "Decorate it with shiny stickers or draw jewels", emoji: "💎" }, { text: "Wrap it around your head and tape the ends together", emoji: "🩹" }] },
  { title: "Handprint Fish", emoji: "🐟", materials: ["Paint", "Paper", "Googly eye", "Markers"], difficulty: "Easy", steps: [{ text: "Paint your whole hand and press it sideways on paper", emoji: "✋" }, { text: "When dry, the fingers become the fish's tail", emoji: "🐠" }, { text: "Glue an eye near the thumb and draw bubbles", emoji: "🫧" }] },
  { title: "Cupcake Liner Snail", emoji: "🐌", materials: ["1 Cupcake liner", "Construction paper", "Glue", "Markers"], difficulty: "Easy", steps: [{ text: "Flatten the cupcake liner and glue it down for the shell", emoji: "🧁" }, { text: "Cut a long, curved shape from paper for the snail's body", emoji: "🐛" }, { text: "Glue the body under the shell and draw antennas", emoji: "📡" }] },
  { title: "Popsicle Stick Star", emoji: "🌟", materials: ["5 Popsicle sticks", "Glue", "Glitter", "String"], difficulty: "Medium", steps: [{ text: "Glue the ends of the sticks together in a star shape", emoji: "⭐" }, { text: "Cover the star with glue and sprinkle glitter on it", emoji: "✨" }, { text: "Tie a string to one point so you can hang it up", emoji: "🎀" }] },
  { title: "Cereal Box Car", emoji: "🚙", materials: ["Empty cereal box", "4 Plastic bottle caps", "Glue", "Paint"], difficulty: "Hard", steps: [{ text: "Paint the cereal box to look like a cool race car", emoji: "🏎️" }, { text: "Glue the bottle caps on the sides to be the wheels", emoji: "🍩" }, { text: "Cut a flap in the top to make a seat for your toys", emoji: "💺" }] },
  { title: "Yarn Wrapped Letters", emoji: "🔠", materials: ["Cardboard", "Colorful yarn", "Scissors", "Tape"], difficulty: "Medium", steps: [{ text: "Cut out the first letter of your name from cardboard", emoji: "✂️" }, { text: "Tape the end of the yarn to the back of the letter", emoji: "🩹" }, { text: "Wrap the yarn tightly around the cardboard until it's covered", emoji: "🧶" }] },
  { title: "Foil River Boat", emoji: "⛵", materials: ["Heavy aluminum foil", "A small stick", "A paper triangle", "Tape"], difficulty: "Medium", steps: [{ text: "Shape the foil into a small bowl or boat shape", emoji: "🥣" }, { text: "Tape the paper triangle to the stick for a sail", emoji: "🚩" }, { text: "Poke the stick through the bottom of the foil boat and test it in water", emoji: "💧" }] },
  { title: "Salt Dough Fossils", emoji: "🦴", materials: ["Salt, flour, water", "Small toy dinosaurs", "Baking sheet"], difficulty: "Hard", steps: [{ text: "Mix salt, flour, and water to make dough", emoji: "🥣" }, { text: "Make flat circles and press toy dinosaurs into them to leave a print", emoji: "🦖" }, { text: "Have an adult bake them until hard so you have fossils!", emoji: "🔥" }] },
  { title: "Bubble Wrap Painting", emoji: "🔴", materials: ["Bubble wrap", "Paint", "Paper"], difficulty: "Easy", steps: [{ text: "Cut a piece of bubble wrap into a fun shape like a heart", emoji: "❤️" }, { text: "Paint the bumpy side with bright colors", emoji: "🎨" }, { text: "Press it onto paper to make cool, dotty artwork", emoji: "🔵" }] },
  { title: "Straw Flute", emoji: "🪈", materials: ["Plastic or paper straws", "Tape", "Scissors"], difficulty: "Medium", steps: [{ text: "Line up 6 straws side by side and tape them together", emoji: "🥤" }, { text: "Cut the bottom of the straws at an angle so they are different lengths", emoji: "✂️" }, { text: "Blow across the top of the straws to hear different notes", emoji: "🎶" }] },
  { title: "Coffee Filter Parachute", emoji: "🪂", materials: ["1 Coffee filter", "String", "A small light toy", "Tape"], difficulty: "Medium", steps: [{ text: "Tape four pieces of string evenly around the edge of the filter", emoji: "🧵" }, { text: "Tie all four strings to your small toy", emoji: "🧸" }, { text: "Drop it from up high and watch it float down safely", emoji: "☁️" }] },
  { title: "Paper Chain Snake", emoji: "🐍", materials: ["Strips of colored paper", "Tape or glue", "Googly eyes"], difficulty: "Easy", steps: [{ text: "Make a loop with one paper strip and tape it shut", emoji: "⭕" }, { text: "Put another strip through the first loop and tape it, keep going!", emoji: "⛓️" }, { text: "On the first loop, glue eyes and a red paper tongue", emoji: "👅" }] }
];

export const getDailyContent = () => {
  return {
    tip: drawingTips[getDailyIndex(drawingTips.length)],
    starter: storyStarters[getDailyIndex(storyStarters.length)],
    craft: craftIdeas[getDailyIndex(craftIdeas.length)]
  };
};
