
import React, { memo } from 'react';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion.jsx";

const faqs = [
  { q: "Are the comics generated by AI?", a: "Yes! Both the daily gag strips and the ongoing PB&J series are generated daily." },
  { q: "Can I read old episodes of PB&J?", a: "Absolutely! Just switch to the PB&J Series tab and scroll down to the archive section." },
  { q: "When are new comics added?", a: "New comics drop every single day at midnight." }
];

const ComicsFAQSection = memo(function ComicsFAQSection() {
  return (
    <section className="py-24 bg-[hsl(var(--bread-tan))] border-b-8 border-black">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <h2 className="text-4xl md:text-6xl font-black comic-font uppercase text-white drop-shadow-[4px_4px_0_#000] text-center mb-12" style={{ WebkitTextStroke: '2px black' }}>FAQ!</h2>
        <Accordion type="single" collapsible className="w-full bg-white border-4 border-black shadow-[8px_8px_0_0_#000] p-4">
          {faqs.map((faq, idx) => (
            <AccordionItem key={idx} value={`item-${idx}`} className="border-b-4 border-black last:border-b-0">
              <AccordionTrigger className="text-xl font-black uppercase text-black hover:text-[hsl(var(--comic-red,350_85%_55%))] py-4">{faq.q}</AccordionTrigger>
              <AccordionContent className="text-lg font-bold text-black pb-4">{faq.a}</AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
});

export default ComicsFAQSection;
